<a href="https://colab.research.google.com/github/vaishnavidahale-cyber/python-assignment/blob/main/Assingment4py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Generate a 4x4 identity matrix
identity_matrix = np.eye(4)
print("4x4 Identity Matrix:\n", identity_matrix)

4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
import numpy as np

# Generate two 3x3 matrices with random integers between 1 and 9
matrix_a = np.random.randint(1, 10, (3, 3))
matrix_b = np.random.randint(1, 10, (3, 3))

print("Matrix A:\n", matrix_a)
print("Matrix B:\n", matrix_b)

# Matrix addition
matrix_addition = np.add(matrix_a, matrix_b)
print("Matrix Addition (A + B):\n", matrix_addition)

# Matrix multiplication
matrix_multiplication = np.dot(matrix_a, matrix_b)
print("Matrix Multiplication (A * B):\n", matrix_multiplication)

In [ ]:
import numpy as np

# Take user input for the 5x3 matrix
matrix_5x3 = []
print("Enter the 5x3 matrix row by row:")
for i in range(5):
    row = list(map(int, input(f"Enter row {i+1}: ").split()))
    matrix_5x3.append(row)

matrix_5x3 = np.array(matrix_5x3)

# Take user input for the 3x2 matrix
matrix_3x2 = []
print("Enter the 3x2 matrix row by row:")
for i in range(3):
    row = list(map(int, input(f"Enter row {i+1}: ").split()))
    matrix_3x2.append(row)

matrix_3x2 = np.array(matrix_3x2)

# Matrix multiplication
product_matrix = np.dot(matrix_5x3, matrix_3x2)
print("Product Matrix (5x3 * 3x2):\n", product_matrix)

Enter the 5x3 matrix row by row:
